const PRODUCTS = [
  {id:'nutella',code:'N-04',name:'Nutella',price:5000,image:'assets/catalog-nutella.webp',gallery:['assets/catalog-nutella.webp','assets/cookie-nutella.jpeg','assets/cookies-closeup.jpeg'],desc:'Masa de vainilla, chips y un centro explosivo de Nutella.',bio:'Una muestra de alta densidad golosa diseñada para liberar chocolate desde el primer corte. Su núcleo fundente permanece protegido por una matriz de vainilla tierna, logrando una reacción prolongada y peligrosamente adictiva.',formula:'Masa de vainilla · chips de chocolate · núcleo de Nutella · cobertura de chocolate.',texture:'Exterior suavemente dorado, centro húmedo y reservorio de Nutella fundida.'},
  {id:'oreo',code:'O-02',name:'Oreo X',price:5000,image:'assets/catalog-oreo.webp',gallery:['assets/catalog-oreo.webp','assets/cookie-oreo.jpeg','assets/gourmet-grid.jpeg'],desc:'Base con Oreo, crema y una generosa carga de chocolate.',bio:'La fórmula O-02 amplifica el contraste clásico de la Oreo: oscuridad de cacao, crema dulce y fragmentos crocantes distribuidos en toda la muestra. El resultado es una cookie XL de comportamiento intenso y final persistente.',formula:'Masa de vainilla · galletas Oreo · chips de chocolate · crema de Oreo.',texture:'Bordes dorados, centro cremoso y partículas crocantes en cada dosis.'},
  {id:'kitkat',code:'K-06',name:'KitKat',price:5000,image:'assets/catalog-kitkat.webp',gallery:['assets/catalog-kitkat.webp','assets/kitkat-batch.jpeg','assets/gourmet-grid.jpeg'],desc:'Masa XL con chocolate y el crocante inconfundible de KitKat.',bio:'Un ensayo de contraste estructural: masa blanda y húmeda atravesada por láminas crocantes de KitKat. La cobertura de chocolate activa una segunda ola de sabor al entrar en temperatura.',formula:'Masa de vainilla · chips · barras KitKat · cobertura de chocolate con leche.',texture:'Centro tierno, inclusiones crocantes y chocolate sedoso en superficie.'},
  {id:'kinder',code:'K-02',name:'Kinder',price:5000,image:'assets/catalog-kinder.webp',gallery:['assets/catalog-kinder.webp','assets/kinder-open.jpeg','assets/cookie-kinder.jpeg'],desc:'Chocolate blanco, chocolate con leche y trozos de Kinder.',bio:'La muestra más equilibrada del laboratorio combina dos fases de chocolate. La fase blanca aporta cremosidad; la fase con leche, intensidad. Los fragmentos Kinder completan una reacción suave, redonda y reconfortante.',formula:'Masa de vainilla · relleno blanco · Kinder · chocolate blanco y con leche.',texture:'Exterior suave, centro cremoso y doble contraste de chocolates.'},
  {id:'chips',code:'C-01',name:'Chips',price:4500,image:'assets/catalog-chips.webp',gallery:['assets/catalog-chips.webp','assets/cookies-closeup.jpeg','assets/gourmet-grid.jpeg'],desc:'La fórmula clásica New York, repleta de chips de chocolate.',bio:'Nuestro patrón de referencia. Una cookie de gran calibre donde la proporción de chips fue calibrada para que cada bocado contenga chocolate sin perder la identidad de la masa. Simple, precisa y siempre efectiva.',formula:'Masa estilo New York · vainilla · chips de chocolate con leche y semiamargo.',texture:'Borde levemente crocante, corazón húmedo y chips fundentes.'},
  {id:'cadbury',code:'C-02',name:'Cadbury Frutilla',price:5000,image:'assets/catalog-cadbury.webp',gallery:['assets/catalog-cadbury.webp','assets/cookies-boxes.jpeg','assets/box-catalog.jpeg'],desc:'Cadbury y crema de frutilla en una combinación irresistible.',bio:'Una reacción frutal inesperada dentro de una matriz de chocolate. La crema de frutilla aporta una nota fresca y dulce que corta la intensidad de la cobertura, creando una muestra de perfil lúdico y muy aromático.',formula:'Masa de vainilla · Cadbury · crema de frutilla · chocolates blanco y con leche.',texture:'Masa tierna, corazón cremoso y cobertura de fusión rápida.'},
  {id:'triple',code:'T-03',name:'Triple Impacto',price:5000,image:'assets/catalog-triple.webp',gallery:['assets/catalog-triple.webp','assets/cookie-triple.jpeg','assets/gourmet-grid.jpeg'],desc:'Doble cacao, corazón cremoso y una explosión de chocolate.',bio:'El protocolo T-03 concentra tres expresiones del cacao en una sola unidad. Es nuestra fórmula de máxima potencia: profunda, húmeda y deliberadamente excesiva. Recomendada para sujetos con tolerancia alta al antojo.',formula:'Cacao amargo 70% · chocolate con leche · chocolate blanco · Hershey’s.',texture:'Exterior intenso, centro húmedo y múltiples focos de chocolate derretido.'}
];
const BOXES={box3:{name:'Box X3 Mixta',size:3,price:14000,premium:false},box6:{name:'Box X6 Mixta',size:6,price:26000,premium:false},box6p:{name:'Box X6 Premium',size:6,price:28000,premium:true}};
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);
let cart=JSON.parse(localStorage.getItem('dorelab-cart-v2')||'[]'); if(!Array.isArray(cart))cart=[];
const grid=document.querySelector('[data-product-grid]'),drawer=document.querySelector('[data-cart-drawer]'),overlay=document.querySelector('[data-overlay]');

grid.innerHTML=PRODUCTS.map(p=>`<article class="product-card" data-view="${p.id}" tabindex="0"><div class="product-image"><img src="${p.image}" alt="Cookie XL ${p.name}" loading="lazy"><span class="product-code">MUESTRA ${p.code}</span></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><b>${money(p.price)}</b><button class="add-button" data-add="${p.id}" aria-label="Agregar ${p.name}">+</button></div></div></article>`).join('');
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function addProduct(id){const found=cart.find(i=>i.kind==='product'&&i.id===id);if(found)found.qty++;else cart.push({uid:uid(),kind:'product',id,qty:1});save();openCart()}
function changeItem(itemUid,amount){const item=cart.find(i=>i.uid===itemUid);if(!item)return;item.qty+=amount;if(item.qty<=0)cart=cart.filter(i=>i.uid!==itemUid);save()}
function save(){localStorage.setItem('dorelab-cart-v2',JSON.stringify(cart));renderCart()}
function itemData(item){if(item.kind==='product'){const p=PRODUCTS.find(x=>x.id===item.id);return{name:p.name,price:p.price,image:p.image,detail:''}}const b=BOXES[item.boxId];const detail=Object.entries(item.selections).filter(([,q])=>q).map(([id,q])=>`${q}× ${PRODUCTS.find(p=>p.id===id).name}`).join(', ');return{name:b.name,price:b.price,image:'assets/box-real.jpeg',detail}}
function renderCart(){const count=cart.reduce((a,i)=>a+i.qty,0);document.querySelector('[data-cart-count]').textContent=count;document.querySelector('[data-cart-empty]').hidden=cart.length>0;document.querySelector('[data-cart-footer]').hidden=cart.length===0;document.querySelector('[data-cart-items]').innerHTML=cart.map(i=>{const d=itemData(i);return `<div class="cart-item"><img src="${d.image}" alt=""><div><h4>${d.name}</h4><small>${d.detail||money(d.price*i.qty)}</small></div><div class="qty"><button data-item-change="${i.uid}" data-amount="-1">−</button><b>${i.qty}</b><button data-item-change="${i.uid}" data-amount="1">+</button></div></div>`}).join('');document.querySelector('[data-cart-total]').textContent=money(cart.reduce((a,i)=>a+itemData(i).price*i.qty,0))}
function openCart(){drawer.classList.add('open');overlay.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeCart(){drawer.classList.remove('open');overlay.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.style.overflow=''}

const productModal=document.querySelector('[data-product-modal]');
function showProduct(id){const p=PRODUCTS.find(x=>x.id===id);document.querySelector('[data-detail-code]').textContent=`EXPEDIENTE ${p.code} · FÓRMULA ORIGINAL`;document.querySelector('[data-detail-name]').textContent=p.name;document.querySelector('[data-detail-bio]').textContent=p.bio;document.querySelector('[data-detail-formula]').textContent=p.formula;document.querySelector('[data-detail-texture]').textContent=p.texture;document.querySelector('[data-detail-price]').textContent=money(p.price);document.querySelector('[data-detail-add]').dataset.add=p.id;const main=document.querySelector('[data-detail-main]');main.src=p.gallery[0];main.alt=`${p.name}, vista principal`;document.querySelector('[data-detail-thumbs]').innerHTML=p.gallery.map((src,i)=>`<button class="${i===0?'active':''}" data-gallery-src="${src}"><img src="${src}" alt="Vista ${i+1} de ${p.name}"></button>`).join('');productModal.showModal()}

const boxModal=document.querySelector('[data-box-modal]');let activeBox=null,boxSelection={};
function openBox(id){activeBox=id;boxSelection={};const b=BOXES[id];document.querySelector('[data-box-title]').textContent=b.name;document.querySelector('[data-box-price]').textContent=money(b.price);renderPicker();boxModal.showModal()}
function renderPicker(){const b=BOXES[activeBox];const list=b.premium?PRODUCTS.filter(p=>p.id!=='chips'):PRODUCTS;const total=Object.values(boxSelection).reduce((a,q)=>a+q,0);document.querySelector('[data-box-count]').textContent=`${total} / ${b.size}`;document.querySelector('[data-box-progress]').style.setProperty('--progress',`${Math.min(total/b.size*100,100)}%`);document.querySelector('[data-add-box]').disabled=total!==b.size;document.querySelector('[data-flavor-picker]').innerHTML=list.map(p=>`<div class="flavor-row"><img src="${p.image}" alt=""><span>${p.name}</span><div class="flavor-counter"><button data-flavor="${p.id}" data-delta="-1">−</button><b>${boxSelection[p.id]||0}</b><button data-flavor="${p.id}" data-delta="1" ${total>=b.size?'disabled':''}>+</button></div></div>`).join('')}
function adjustFlavor(id,delta){const b=BOXES[activeBox],total=Object.values(boxSelection).reduce((a,q)=>a+q,0);if(delta>0&&total>=b.size)return;boxSelection[id]=Math.max(0,(boxSelection[id]||0)+delta);renderPicker()}
function addBox(){const b=BOXES[activeBox],total=Object.values(boxSelection).reduce((a,q)=>a+q,0);if(total!==b.size)return;cart.push({uid:uid(),kind:'box',boxId:activeBox,selections:{...boxSelection},qty:1});save();boxModal.close();openCart()}

document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){e.stopPropagation();addProduct(add.dataset.add);return}const view=e.target.closest('[data-view]');if(view)showProduct(view.dataset.view);const ch=e.target.closest('[data-item-change]');if(ch)changeItem(ch.dataset.itemChange,Number(ch.dataset.amount));const thumb=e.target.closest('[data-gallery-src]');if(thumb){document.querySelector('[data-detail-main]').src=thumb.dataset.gallerySrc;document.querySelectorAll('[data-gallery-src]').forEach(x=>x.classList.toggle('active',x===thumb))}const box=e.target.closest('[data-open-box]');if(box)openBox(box.dataset.openBox);const flavor=e.target.closest('[data-flavor]');if(flavor)adjustFlavor(flavor.dataset.flavor,Number(flavor.dataset.delta));if(e.target.closest('[data-open-cart]'))openCart();if(e.target.closest('[data-close-cart]')||e.target===overlay)closeCart()});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-view]'))showProduct(e.target.dataset.view)});
document.querySelector('[data-close-product]').addEventListener('click',()=>productModal.close());document.querySelector('[data-close-box]').addEventListener('click',()=>boxModal.close());document.querySelector('[data-add-box]').addEventListener('click',addBox);
document.querySelector('[data-checkout]').addEventListener('click',()=>{const lines=cart.map(i=>{const d=itemData(i);return `• ${i.qty} × ${d.name} — ${money(d.price*i.qty)}${d.detail?`\n  Combinación: ${d.detail}`:''}`});const total=cart.reduce((a,i)=>a+itemData(i).price*i.qty,0),delivery=document.querySelector('[data-delivery]').value;const message=`¡Hola Doré Lab! 🧪 Quiero hacer este pedido:\n\n${lines.join('\n')}\n\nTotal productos: ${money(total)}\nModalidad: ${delivery}\n\n¿Me confirman disponibilidad y coordinación?`;window.open(`https://wa.me/5491135231567?text=${encodeURIComponent(message)}`,'_blank')});

const cakeModal=document.querySelector('[data-cake-modal]');document.querySelector('[data-open-cake]').addEventListener('click',()=>cakeModal.showModal());document.querySelector('[data-close-cake]').addEventListener('click',()=>cakeModal.close());document.querySelector('[data-cake-form]').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const message=`¡Hola Doré Lab! 🎂 Quiero cotizar una torta personalizada.\n\n• Porciones: ${data.get('porciones')||'A definir'}\n• Sabores: ${data.get('sabores')||'A definir'}\n• Fecha: ${data.get('fecha')||'A definir'}\n• Idea: ${data.get('idea')||'Quiero que me asesoren'}\n\n¿Podemos crear esta fórmula?`;window.open(`https://wa.me/5491135231567?text=${encodeURIComponent(message)}`,'_blank')});
renderCart();


